version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fraud-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    build: ./frontend
    container_name: fraud-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
